#!/usr/bin/perl
# Copyright 2015 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib/perl";
use Config::Simple;
use ZBH::SGE;

sub main ($ $ $ $ $) {

	my $starter = shift;
	my $configfile1 = shift;
	my $configfile2 = shift;
	my $logfile1 = shift;
	my $logfile2 = shift;

	my $config1 = new Config::Simple($configfile1);
	my $output1 =  $config1->param( "result.output");
	
	my $config2 = new Config::Simple($configfile2);
	my $output2 =  $config2->param( "result.output");

	return ("started") if ( ZBH::SGE::is_background_process_sge($starter));

	unlink($logfile1, $output1, $logfile2, $output2);

	system("qsub -S /bin/bash -wd $FindBin::Bin $starter $configfile1 $output1");
	system("qsub -S /bin/bash -wd $FindBin::Bin $starter $configfile2 $output2");

	return ("wait");
}

exit(
	print(
		main(
			"$FindBin::Bin/bin/imbiss.sh",
			"$FindBin::Bin/etc/sequence.cnf",
			"$FindBin::Bin/etc/structure.cnf",			
			"$FindBin::Bin/log/sequence.log",
			"$FindBin::Bin/log/structure.log",
		)
	)
);
